import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    'help',
    'faq',
    {
      type: 'category',
      label: "Developers",
      link: {
        type: "generated-index",
        description: "Building with Stoat"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'developers',
        }
      ]
    },
    {
      type: 'category',
      label: "Developing Stoat",
      link: {
        type: "generated-index",
        description: "Building Stoat"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'developing',
        },
        {
          type: 'link',
          label: "for Web",
          href: "https://stoatchat.github.io/for-web"
        },
        {
          type: 'link',
          label: "for Android",
          href: "https://stoatchat.github.io/for-android"
        }
      ]
    }
  ],
};

export default sidebars;
